---
- name: update apt
  apt: update_cache=yes

- name: ensure sudo is installed
  apt: pkg=sudo state=present

- name: install base packages
  apt: pkg={{ item }} state=installed
  with_items:
    - vim
    - wget
    - git
    - curl
    - ntp
    - fail2ban

- include: firewall.yml
- include: ssh-settings.yml
- include: automatic-updates.yml