---
- name: install nginx
  apt: pkg=nginx state=present

- name: load the configuration file
  template: src=wordpress.conf.j2 dest=/etc/nginx/sites-available/default
  notify: restart nginx

- name: ensure nginx is enabled
  service: name=nginx enabled=yes