---
- name: download php
  apt_repository: repo=ppa:ondrej/php5-{{ php_version }}

- name: install php5 packages
  apt: pkg={{ item }} state=present
  with_items:
    - php5
    - php5-fpm
    - php5-intl
    - php5-mcrypt
    - php5-mysql

- name: secure php-fpm from script injections
  lineinfile: >
    dest=/etc/php5/fpm/php.ini
    regexp="cgi.fix_pathinfo="
    line="cgi.fix_pathinfo=0"
  notify: restart php5-fpm

- name: esnure php5-fpm is running
  service: name=php5-fpm enabled=true