---
- name: install redis
  apt: pkg={{ item }} state=present
  with_items:
    - redis-server
    - php5-redis

- name: allocate memory for redis
  lineinfile: >
    dest=/etc/redis/redis.conf
    line='maxmemory 256mb'

- name: allocate memory for redis
  lineinfile: >
    dest=/etc/redis/redis.conf
    line='maxmemory 256mb'

- name: turn on LRU for redis to manage cache memory
  lineinfile: >
    dest=/etc/redis/redis.conf
    line='maxmemory-policy allkeys-lru'